sudo: false
install: true

## Lenguaje de la app
language: java
## Sistema operativo
os: linux

## Install java
jdk: oraclejdk9

## Scripts
script:
  - mvn clean install

cache:
  directories:
    - $HOME/.m2/repository