trigger:
  - main
  - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables-pipelines.yml

stages:
  - stage: Development
    displayName: Stage Development
    jobs:
      - job: Maven
        displayName: Maven job
        steps:
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(mavenCacheFolder)
            displayName: Cache Maven
          - task: Maven@3
            displayName: 'Validar estructura maven'
            inputs:
              goals: validate
              options: '-Dmaven.test.skip=true'
              publishJUnitResults: false
              checkStyleRunAnalysis: true
      - job: Test
        displayName: Test job
        steps:
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(mavenCacheFolder)
            displayName: Cache Maven
          - task: SonarCloudPrepare@1
            displayName: 'Preparar análisis en SonarCloud'
            inputs:
              SonarCloud: 'mpluasgu_ms-prueba-cloud'
              organization: 'mpluasgu'
              scannerMode: Other
          - task: Maven@3
            displayName: 'Pruebas unitarias'
            inputs:
              goals: verify
              options: 'sonar:sonar -Dsonar.projectKey=$(sonarKeyProject)'
              testResultsFiles: '**/TEST-*.xml'
              codeCoverageToolOption: JaCoCo
              codeCoverageRestoreOriginalPomXml: true
              sonarQubeRunAnalysis: true
              isJacocoCoverageReportXML: true
              sqMavenPluginVersionChoice: pom
              checkStyleRunAnalysis: true
          - task: SonarCloudPublish@1
            displayName: 'Publicar los resultados en el resumen de la compilación'
            inputs:
              pollingTimeoutSec: '300'
