trigger:
  - main
  - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables-pipelines.yml

stages:
  - stage: Development
    displayName: Stage Development
    jobs:
      - job: Maven
        displayName: Maven job
        steps:
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(mavenCacheFolder)
            displayName: Cache maven
          - task: Maven@3
            displayName: Validate maven structure
            inputs:
              goals: validate
              options: '-Dmaven.test.skip=true'
              publishJUnitResults: false
      - job: Test
        displayName: Test job
        dependsOn: Maven
        steps:
          - task: SonarCloudPrepare@1
            displayName: Prepare analysis in SonarCloud
            inputs:
              SonarCloud: 'mpluasgu_ms-prueba-cloud'
              organization: 'mpluasgu'
              scannerMode: Other
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(mavenCacheFolder)
            displayName: Cache maven
          - task: Maven@3
            displayName: Unit tests
            inputs:
              goals: test
              options: '-Dsonar.projectKey=$(sonarKeyProject)'
              testResultsFiles: '**/TEST-*.xml'
              codeCoverageToolOption: JaCoCo
              codeCoverageRestoreOriginalPomXml: true
              sonarQubeRunAnalysis: true
              isJacocoCoverageReportXML: true
          - task: SonarCloudPublish@1
            displayName: Publish the results to the build summary
            inputs:
              pollingTimeoutSec: '300'
          - task: PublishCodeCoverageResults@1
            displayName: Publish code coverage
            inputs:
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/jacoco.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/**/site/jacoco'
              additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/**/*.exec'

  - stage: Build
    displayName: Stage Build
    dependsOn: Development
    jobs:
      - job: Download
        displayName: Download Repository job
        steps:
          - task: CopyFilesOverSSH@0
            displayName: Securely copy files to the remote machine
            inputs:
              sshEndpoint: marlonpluasvm1
              targetFolder: deploy
      - job: Build
        displayName: Build Container job
        steps:
          - powershell: |
              [xml]$pomXml = Get-Content .\pom.xml
              # artifactId
              Write-Host $pomXml.project.artifactId
              $artifactId=$pomXml.project.artifactId
              Write-Host "##vso[task.setvariable variable=artifactId]$artifactId"
              # version
              Write-Host $pomXml.project.version
              $version=$pomXml.project.version
              Write-Host "##vso[task.setvariable variable=version]$version"
              # packaging
              Write-Host $pomXml.project.packaging
              $packaging=$pomXml.project.packaging
              Write-Host "##vso[task.setvariable variable=packaging]$packaging"
              # nombreImagen
              $nombreImagen=$artifactId+":"+$version
              Write-Host $nombreImagen
              Write-Host "##vso[task.setvariable variable=nombreImagen]$nombreImagen"
            displayName: Initializing variables
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(mavenCacheFolder)
            displayName: Cache maven
          - task: Maven@3
            displayName: Generate dependencies
            inputs:
              goals: package
              options: '-Dmaven.test.skip=true'
              publishJUnitResults: false
          - task: Docker@2
            displayName: Login container registry
            inputs:
              containerRegistry: marlonpluasregistry
              command: login
          - task: Cache@2
            inputs:
              key: 'docker | "$(Agent.OS)" | caching-docker.yml'
              path: $(Pipeline.Workspace)/docker
              cacheHitVar: DOCKER_CACHE_RESTORED
            displayName: Caching Docker image

          - script: |
              docker load < $(Pipeline.Workspace)/docker/cache.tar
            condition: and(not(canceled()), eq(variables.DOCKER_CACHE_RESTORED, 'true'))

          - script: |
              mkdir -p $(Pipeline.Workspace)/docker
              docker pull $(artifactId)
              docker save $(artifactId) > $(Pipeline.Workspace)/docker/cache.tar
            condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_RESTORED, 'true')))
          - task: Docker@2
            displayName: Build docker image $(nombreImagen)
            inputs:
              containerRegistry: marlonpluasregistry
              repository: $(artifactId)
              command: build
              tags: $(version)
              arguments: '--build-arg artifactId=$(artifactId) --build-arg version=$(version)'
          - task: Docker@2
            displayName: Push docker image $(nombreImagen)
            inputs:
              containerRegistry: marlonpluasregistry
              repository: $(artifactId)
              command: push
              tags: $(version)

  - stage: Deploy_Test
    displayName: Stage Deploy Test
    dependsOn: Build
    condition: and(succeeded(), eq(variables.branch, 'main'))
    jobs:
      - job: Deploy
        displayName: Deploy job
        steps:
          - task: SSH@0
            displayName: 'Run shell commands on remote machine'
            inputs:
              sshEndpoint: marlonpluasvm1
              commands: |
                cd deploy
                docker service rm $(serviceDeploy)
                docker stack deploy -c docker-compose.yml $(keySwarmDeploy)

  - stage: Deploy_Prod
    displayName: Stage Deploy Prod
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy job
        steps:
          - task: SSH@0
            displayName: Validate and remove swarm service
            inputs:
              sshEndpoint: marlonpluasvm1
              commands: |
                cd deploy
                docker service rm $(serviceDeploy)
              failOnStdErr: false
            continueOnError: true
          - task: SSH@0
            displayName: Deploy swarm service
            inputs:
              sshEndpoint: marlonpluasvm1
              commands: |
                cd deploy
                env NOMBRE_IMAGEN=$(nombreImagen) docker stack deploy -c docker-compose.yml $(keySwarmDeploy)