trigger:
- main
- feature/*

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
  branch: variables['Build.SourceBranch']

stages:
- stage: Stage Maven
  displayName: Stage Maven
  jobs:
  - job: Maven
    displayName: Maven job
    steps:
    - task: Cache@2
      inputs:
        key: '"funcs" | maven |"$(Agent.OS)" | **/pom.xml'
        restoreKeys: |
        path: $(MAVEN_CACHE_FOLDER)
      displayName: Cache Maven local repo

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

- stage: Stage Copy
  displayName: Stage Copy
  condition: and(succeeded(), eq(variables.branch, 'test'))
  jobs:
  - job: Copy
    displayName: Copy job
    steps:
    - task: CopyFilesOverSSH@0
      displayName: 'Securely copy files to the remote machine'
      inputs:
        sshEndpoint: marlonpluasvm1
        targetFolder: deploy


