pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables-pipelines.yml
  - ${{ if eq(variables['Build.SourceBranch'], 'main') }}:
      - group: group-prod
  - ${{ if ne(variables['Build.SourceBranch'], 'main') }}:
      - group: group-test

stages:
  - stage: Build
    displayName: Stage Build
    #dependsOn: Development_Test
    jobs:
      - job: Download
        displayName: Download Repository job
        steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: Replace tokens
            inputs:
              targetFiles: |
                **/application.properties.dist
          - task: CopyFilesOverSSH@0
            displayName: Securely copy files to the remote machine prod
            condition: and(succeeded(), eq(variables.isMain, true))
            inputs:
              sshEndpoint: marlonpluasvm1
              ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
                targetFolder: $(keySwarmDeploy)_$(serviceSwarm)
              ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
                targetFolder: $(keySwarmDeployTest)_$(serviceSwarm)
          - task: CopyFilesOverSSH@0
            displayName: Securely copy files to the remote machine test
            condition: and(succeeded(), ne(variables.isMain, true))
            inputs:
              sshEndpoint: marlonpluasvm3
              ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
                targetFolder: $(keySwarmDeploy)_$(serviceSwarm)
              ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
                targetFolder: $(keySwarmDeployTest)_$(serviceSwarm)
      - job: Build
        displayName: Build Container job
        steps:
          - powershell: |
              [xml]$pomXml = Get-Content .\pom.xml
              # artifactId
              Write-Host $pomXml.project.artifactId
              $artifactId=$pomXml.project.artifactId
              Write-Host "##vso[task.setvariable variable=artifactId]$artifactId"
              # version
              Write-Host $pomXml.project.version
              $version=$pomXml.project.version
              Write-Host "##vso[task.setvariable variable=version]$version"
              # packaging
              Write-Host $pomXml.project.packaging
              $packaging=$pomXml.project.packaging
              Write-Host "##vso[task.setvariable variable=packaging]$packaging"
              # nombreImagen
              $nombreImagen=$artifactId
              Write-Host $nombreImagen
              Write-Host "##vso[task.setvariable variable=nombreImagen]$nombreImagen"
              Write-Host $(Build.SourceBranchName)
              # tagImagen
              if ('$(Build.SourceBranchName)' -eq 'main')
              {
                $tagImagen="latest"
              }
              else
              {
                $tagImagen=$version
              }
              Write-Host $tagImagen
              Write-Host "##vso[task.setvariable variable=tagImagen]$tagImagen"
            displayName: Initializing variables
          - task: Cache@2
            inputs:
              key: '"funcs" | maven |"$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(mavenCacheFolder)
            displayName: Cache maven
          - task: Maven@3
            displayName: Generate dependencies
            inputs:
              goals: package
              options: '-Dmaven.test.skip=true'
              publishJUnitResults: false
          - task: Docker@2
            displayName: Login container registry
            inputs:
              containerRegistry: marlonpluasregistry
              command: login
          - script: "docker pull $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)"
            displayName: Pull image for caching
            continueOnError: true # for first build, no cache
          - task: Docker@2
            displayName: Build docker image
            inputs:
              containerRegistry: marlonpluasregistry
              repository: $(nombreImagen)
              command: build
              tags: $(tagImagen)
              arguments: '--build-arg artifactId=$(artifactId) --build-arg version=$(version) --cache-from=$(hostDockerRegistry)/$(nombreImagen):$(tagImagen)'
          - task: Docker@2
            displayName: Push docker image
            inputs:
              containerRegistry: marlonpluasregistry
              repository: $(nombreImagen)
              command: push
              tags: $(tagImagen)

  - stage: Releases
    displayName: Stage Releases
    dependsOn: Build
    jobs:
      - job: Releases
        displayName: Releases job
        steps:
          - powershell: |
              [xml]$pomXml = Get-Content .\pom.xml
              # artifactId
              Write-Host $pomXml.project.artifactId
              $artifactId=$pomXml.project.artifactId
              Write-Host "##vso[task.setvariable variable=artifactId]$artifactId"
              # version
              Write-Host $pomXml.project.version
              $version=$pomXml.project.version
              Write-Host "##vso[task.setvariable variable=version]$version"
              # packaging
              Write-Host $pomXml.project.packaging
              $packaging=$pomXml.project.packaging
              Write-Host "##vso[task.setvariable variable=packaging]$packaging"
              # nombreImagen
              $nombreImagen=$artifactId
              Write-Host $nombreImagen
              Write-Host "##vso[task.setvariable variable=nombreImagen]$nombreImagen"
              # tagImagen
              if ('$(Build.SourceBranchName)' -eq 'main')
              {
                $tagImagen="latest"
              }
              else
              {
                $tagImagen=$version
              }
              Write-Host $tagImagen
              Write-Host "##vso[task.setvariable variable=tagImagen]$tagImagen"
            displayName: Initializing variables
          - task: SSH@0
            displayName: Pull image Prod VM1
            condition: and(succeeded(), eq(variables.isMain, true))
            inputs:
              sshEndpoint: marlonpluasvm1
              commands: |
                docker rmi -f $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)
                docker pull $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)
              failOnStdErr: false
          - task: SSH@0
            displayName: Pull image Prod VM2
            condition: and(succeeded(), eq(variables.isMain, true))
            inputs:
              sshEndpoint: marlonpluasvm2
              commands: |
                docker rmi -f $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)
                docker pull $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)
              failOnStdErr: false
          - task: SSH@0
            displayName: Pull image Test VM3
            condition: and(succeeded(), ne(variables.isMain, true))
            inputs:
              sshEndpoint: marlonpluasvm3
              commands: |
                docker rmi -f $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)
                docker pull $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)
              failOnStdErr: false
          - task: SSH@0
            displayName: Pull image Test VM4
            condition: and(succeeded(), ne(variables.isMain, true))
            inputs:
              sshEndpoint: marlonpluasvm4
              commands: |
                docker rmi -f $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)
                docker pull $(hostDockerRegistry)/$(nombreImagen):$(tagImagen)
              failOnStdErr: false

  - stage: Deploy_Test
    displayName: Stage Deploy Test
    dependsOn: Releases
    condition: and(succeeded(), ne(variables.isMain, true))
    jobs:
      - job: Deploy
        displayName: Deploy job
        steps:
          - powershell: |
              [xml]$pomXml = Get-Content .\pom.xml
              # artifactId
              Write-Host $pomXml.project.artifactId
              $artifactId=$pomXml.project.artifactId
              Write-Host "##vso[task.setvariable variable=artifactId]$artifactId"
              # version
              Write-Host $pomXml.project.version
              $version=$pomXml.project.version
              Write-Host "##vso[task.setvariable variable=version]$version"
              # packaging
              Write-Host $pomXml.project.packaging
              $packaging=$pomXml.project.packaging
              Write-Host "##vso[task.setvariable variable=packaging]$packaging"
              # nombreImagen
              $nombreImagen=$artifactId
              Write-Host $nombreImagen
              Write-Host "##vso[task.setvariable variable=nombreImagen]$nombreImagen"
              # tagImagen
              if ('$(Build.SourceBranchName)' -eq 'main')
              {
                $tagImagen="latest"
              }
              else
              {
                $tagImagen=$version
              }
              Write-Host $tagImagen
              Write-Host "##vso[task.setvariable variable=tagImagen]$tagImagen"
            displayName: Initializing variables
          - task: SSH@0
            displayName: Validate and remove swarm service
            inputs:
              sshEndpoint: marlonpluasvm3
              commands: |
                docker service rm $(keySwarmDeployTest)_$(serviceSwarm)
                docker service rm sso_haproxy
              failOnStdErr: false
            continueOnError: true
          - task: SSH@0
            displayName: Deploy swarm service
            inputs:
              sshEndpoint: marlonpluasvm3
              commands: |
                cp $(pwd)/$(keySwarmDeployTest)_$(serviceSwarm)/$(properties).dist $(pwd)/$(keySwarmDeployTest)_$(serviceSwarm)/$(properties)
                env PWD=$(pwd)/$(keySwarmDeployTest)_$(serviceSwarm) env PUERTO_INT=$(puertoInt) env PUERTO_EXT=$(puertoExtTest) env NOMBRE_IMAGEN=$(hostDockerRegistry)/$(nombreImagen):$(tagImagen) env REPLICAS=$(numReplicasSwarm) docker stack deploy -c $(keySwarmDeployTest)_$(serviceSwarm)/docker-compose.yml $(keySwarmDeployTest)
                docker stack deploy -c $(pwd)/haproxy/docker-compose.yml sso

  - stage: Deploy_Prod
    displayName: Stage Deploy Prod
    dependsOn: Releases
    condition: and(succeeded(), eq(variables.isMain, true))
    jobs:
      - job: Deploy
        displayName: Deploy job
        steps:
          - powershell: |
              [xml]$pomXml = Get-Content .\pom.xml
              # artifactId
              Write-Host $pomXml.project.artifactId
              $artifactId=$pomXml.project.artifactId
              Write-Host "##vso[task.setvariable variable=artifactId]$artifactId"
              # version
              Write-Host $pomXml.project.version
              $version=$pomXml.project.version
              Write-Host "##vso[task.setvariable variable=version]$version"
              # packaging
              Write-Host $pomXml.project.packaging
              $packaging=$pomXml.project.packaging
              Write-Host "##vso[task.setvariable variable=packaging]$packaging"
              # nombreImagen
              $nombreImagen=$artifactId
              Write-Host $nombreImagen
              Write-Host "##vso[task.setvariable variable=nombreImagen]$nombreImagen"
              # tagImagen
              if ('$(Build.SourceBranchName)' -eq 'main')
              {
                $tagImagen="latest"
              }
              else
              {
                $tagImagen=$version
              }
              Write-Host $tagImagen
              Write-Host "##vso[task.setvariable variable=tagImagen]$tagImagen"
            displayName: Initializing variables
          - task: SSH@0
            displayName: Validate and remove swarm service
            inputs:
              sshEndpoint: marlonpluasvm1
              commands: |
                docker service rm $(keySwarmDeploy)_$(serviceSwarm)
                docker service rm sso_haproxy
              failOnStdErr: false
            continueOnError: true
          - task: SSH@0
            displayName: Deploy swarm service
            inputs:
              sshEndpoint: marlonpluasvm1
              commands: |
                cp $(pwd)/$(keySwarmDeploy)_$(serviceSwarm)/$(properties).dist $(pwd)/$(keySwarmDeploy)_$(serviceSwarm)/$(properties)
                env PWD=$(pwd)/$(keySwarmDeploy)_$(serviceSwarm) env PUERTO_INT=$(puertoInt) env PUERTO_EXT=$(puertoExt) env NOMBRE_IMAGEN=$(hostDockerRegistry)/$(nombreImagen):$(tagImagen) env REPLICAS=$(numReplicasSwarm) docker stack deploy -c $(keySwarmDeploy)_$(serviceSwarm)/docker-compose.yml $(keySwarmDeploy)
                docker stack deploy -c $(pwd)/haproxy/docker-compose.yml sso