trigger:
  - main
  - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  mavenCacheFolder: $(HOME)/.m2/repository
  branch: $(Build.Repository.Name)
  serviceDeploy1: nginx
  serviceDeploy: nginx_nginx

stages:
  - stage: Maven
    displayName: Stage Maven
    jobs:
      - job: Maven
        displayName: Maven job
        steps:
          - task: Cache@2
            inputs:
              key: '"funcs" | maven |"$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
              path: $(mavenCacheFolder)
            displayName: Cache Maven local repo

          - task: SonarCloudPrepare@1
            displayName: 'Prepare analysis on SonarCloud'
            inputs:
              SonarCloud: 'mpluasgu_ms-prueba-cloud'
              organization: 'mpluasgu_ms-prueba-cloud'
              scannerMode: Other

          - task: Maven@3
            displayName: 'Execute Maven goal'
            inputs:
              mavenPomFile: 'pom.xml'
              options: '-Dmaven.test.failure.ignore=true'
              mavenOptions: '-Xmx3072m'
              mavenVersionOption: 'Default'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'latest'
              codeCoverageToolOption: 'JaCoCo'
              testResultsFiles: '**/TEST-*.xml'
              goals: 'verify'

          - task: SonarCloudPublish@1
            displayName: 'Publish results on build summary'
            inputs:
              pollingTimeoutSec: '300'

  - stage: Copy
    displayName: Stage Copy
    jobs:
      - job: Copy
        displayName: Copy job
        steps:
          - task: CopyFilesOverSSH@0
            displayName: 'Securely copy files to the remote machine'
            inputs:
              sshEndpoint: marlonpluasvm1
              targetFolder: deploy

  - stage: Deploy_Test
    displayName: Stage Deploy Test
    dependsOn: Copy
    condition: and(succeeded(), eq(variables.branch, 'main'))
    jobs:
      - job: Deploy
        displayName: Deploy job
        steps:
          - task: SSH@0
            displayName: 'Run shell commands on remote machine'
            inputs:
              sshEndpoint: marlonpluasvm1
              commands: |
                cd deploy
                docker service rm $(serviceDeploy)
                docker stack deploy -c docker-compose.yml $(serviceDeploy1)

  - stage: Deploy_Prod
    displayName: Stage Deploy Prod
    dependsOn: Copy
    jobs:
      - job: Deploy
        displayName: Deploy job
        steps:
          - task: SSH@0
            displayName: 'Run shell commands on remote machine'
            inputs:
              sshEndpoint: marlonpluasvm1
              commands: |
                cd deploy
                docker service rm $(serviceDeploy)
                docker stack deploy -c docker-compose.yml $(serviceDeploy1)

