version: '3.5'

services:
  cloud:
    image: $NOMBRE_IMAGEN
    ports:
      - '$PUERTO_EXT:$PUERTO_INT'
    volumes:
      - "$PWD/application.properties:/application.properties"
      #- "$PWD/log4j2.xml:/log4j2.xml"
    deploy:
      replicas: $REPLICAS